# Generated by Django 4.2.11 on 2024-05-24 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 24, 10, 17, 52, 267157, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 24, 10, 17, 52, 267157, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
